name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v8
      - name: Cachix
        uses: cachix/cachix-action@v5
        with:
          name: meros
          skipNixBuild: true
      - name: Build
        run: 'nix-build --quiet -I nixpkgs=https://github.com/mkg20001/nixpkgs/archive/mkg-patch.tar.gz -A nixinstall'

  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
